var mongoose = require('mongoose');
var Schema   = mongoose.Schema;

var Internnexusproject = new Schema(
    {
        userid:{
            type:String
          },
          username:{
              type:String
          },
          email:{
              type:String
          },
          projectid:{
              type:String
          },
          projectid1:{
            type:String
          },
          projectid2:{
            type:String
          },
          projectname :{
            type:String
        },
        technologyused:{
            type:String
          },
          level:{
            type:String
        },
        duration:{
            type:String
          },
          fees:{
            type:String
        },
        projectbrief:{
            type:String
          },
          pdflink:{
            type:String
          },
          guideverify:{
            type:String,
            default:false
          },  
          guide:{
            type:String
        },
        guideemail:{
            type:String
        },
        guidereview:{
            type:String
        },
        applydate:{
            type:Date
        },
        expirydate:{
            type:Date
        },
        applydate1:{
            type:String
        },
        expirydate1:{
            type:String
        },
        submitproject:{
            type:String,
            default:false
        },
        submitprojectverified:{
            type:String,
            default:false
        },
        finalproject:{
            type:String,
            default:false
        },
        githublink:{
            type:String
        },
        livedomainlink:{
            type:String
        }
    }
);

mongoose.model('Internnexusproject', Internnexusproject);
